### ISSUE TITLE
Smaller issues on getting started.

### ISSUE THREAD

**Issue by Andre601** [kangarko/CompatBridge#1]
Right now I have some smaller issues with getting this api to work inside my plugin.

### Issue 1: Wrong/Not available versions
The readme mentions the version to be 2.0.0 (And so does also the spigot page.) but right now the only version I can get is the one from the releases which as of now is only 1.0.4.
I recommend to have a label or something in the readme, that would show the current version.

### Issue 2: `CompatBridge#setPlugin();` doesn't exist
I can't get `CompatBridge#getPlugin()` to use.
I did it like this (Note that Example is just a placeholder for the real plugin name):
```java
public class Example extends JavaPlugin{
    private CompatBridge compatBridge;

    @Override
    public void onEnable(){
        compatBridge = new CompatBridge().setPlugin(this);
    }
```
But `setPlugin` doesn't seem to exist at all (I refer to what is mentioned on the spigot page).

Please add a sort of documentation (Perhaps some wiki pages in this repository) on how to properly start with this API.
Thanks.

**Comment by kangarko** [comment]
Hey,

regarding Issue 1, we will be removing the Releases page soon, it is there temporarily with an older version because I teach this material in spigotcourse.org

Issue 2: Just download the entire repository as a ZIP. It is there in the latest version: https://github.com/kangarko/CompatBridge/blob/master/src/main/java/me/kangarko/compatbridge/CompatBridge.java#L313

**Comment by kangarko** [comment]
As for the docs, the library is fully documented and once you setPlugin in CompatBridge it should be fairly self-explanatory, since we have full javadocs everywhere.

I recommend you take a look at https://github.com/kangarko/CompatBridge/tree/master/src/main/java/me/kangarko/compatbridge/model to see the classes we made compatible according to their Bukkit counterparts

**Comment by kangarko** [comment]
Finally, you don't make new instance of any class in this plugin, you simply call CompatBridge.setPlugin(yourJavaPlugin) using static access

**Comment by Andre601** [comment]
How would I go about importing it as a library/API?
I use IntelliJ to be clear and I know how you can import jar-files, but not what would be the difference for zips.

**Comment by Andre601** [comment]
Also it's nice and all that there are javadocs, but this doesn't answer fundamental questions people will have like "How do I make people use 1.12 and 1.13 material names?" and Javadocs can only answer that much.

There can be the case where you use a method, that shouldn't be used, or that should be the last method to use at all.
So a simple wiki-page that explains stuff like "How to use with materials", "how to use with dye colours", etc. would be a good start for most people.
Just go and say "Yeah it's in the javadocs. Read those" leaves people hanging and only costs more time than it should.

**Comment by kangarko** [comment]
How is the readme misleading? If you are using Maven you simply use it as a dependency and the **compile score** will make sure the library is automatically included in your plugin jar when you build it.

If you don't use Maven nor Gradle but simply importing to Jar, I'm afraid I can't help you shade the lib inside automatically, you'd have to download it and place the packages to your source folder manually but that's not recommended.

You can use CompMaterial instead of Material to make calls for material names between all MC versions.

Thanks, will look into creating a wiki.
